language: node_js
os:
  - linux
  - osx
  - windows
node_js:
  - 10.15
install:
  - npm install
  - npm run build
cache:
  directories:
    - node_modules
addons:
  apt:
    update: true
git:
  depth: false
