language: node_js
os:
  - linux
  - osx
  - windows
node_js:
  - 10.15
before_install:
  - curl https://sh.rustup.rs > rustup.sh && chmod +x rustup.sh && ./rustup.sh -y
install:
  - PATH="$PATH:$HOME/.cargo/bin" npm install
  - PATH="$PATH:$HOME/.cargo/bin" npm run build
cache:
  directories:
    - node_modules
    - "$HOME/.cargo"
addons:
  apt:
    update: true
git:
  depth: false
