language: node_js
os:
  - linux
  - osx
  - windows
node_js:
  - 10.15
  - eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64"
install:
  - npm install
  - npm run build
  - npm run install
cache:
  directories:
    - node_modules
addons:
  apt:
    update: true
git:
  depth: false
